import type { MediaItem } from './types';

export const INITIAL_MEDIA: MediaItem[] = [
  {
    id: 'tt0111161',
    title: 'The Shawshank Redemption',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg',
    data_ai_hint: 'prison drama',
    year: '1994',
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    imdbRating: '9.3',
    genre: ['Drama'],
    plot: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    watched: true,
  },
  {
    id: 'tt0816692',
    title: 'Interstellar',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    data_ai_hint: 'space astronaut',
    year: '2014',
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    imdbRating: '8.7',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    watched: false,
  },
    {
    id: 'tt0903747',
    title: 'Breaking Bad',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzNjHYTllOTE2YjMabelleXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg',
    data_ai_hint: 'desert chemistry',
    year: '2008–2013',
    director: 'Vince Gilligan (Creator)',
    actors: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    imdbRating: '9.5',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    watched: true,
  },
  {
    id: 'tt7366338',
    title: 'Chernobyl',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BZGQ2YmMxZmEtYjI5OS00NzlkLTlkNTEtYWMyMzkyMzc2MDU5XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SX300.jpg',
    data_ai_hint: 'nuclear disaster',
    year: '2019',
    director: 'Johan Renck',
    actors: ['Jessie Buckley', 'Jared Harris', 'Stellan Skarsgård'],
    imdbRating: '9.4',
    genre: ['Drama', 'History', 'Thriller'],
    plot: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world\'s worst man-made catastrophes.',
    watched: false,
  },
];

export const ALL_MEDIA: MediaItem[] = [
  ...INITIAL_MEDIA,
  {
    id: 'tt0468569',
    title: 'The Dark Knight',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
    data_ai_hint: 'city hero',
    year: '2008',
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    imdbRating: '9.0',
    genre: ['Action', 'Crime', 'Drama'],
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    watched: false,
  },
  {
    id: 'tt1375666',
    title: 'Inception',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    data_ai_hint: 'city spinning',
    year: '2010',
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    imdbRating: '8.8',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    watched: false,
  },
  {
    id: 'tt0133093',
    title: 'The Matrix',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    data_ai_hint: 'green code',
    year: '1999',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    imdbRating: '8.7',
    genre: ['Action', 'Sci-Fi'],
    plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    watched: false,
  },
  {
    id: 'tt0944947',
    title: 'Game of Thrones',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg',
    data_ai_hint: 'iron throne',
    year: '2011–2019',
    director: 'David Benioff (Creator), D.B. Weiss (Creator)',
    actors: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington'],
    imdbRating: '9.2',
    genre: ['Action', 'Adventure', 'Drama'],
    plot: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    watched: false,
  },
  {
    id: 'tt2861424',
    title: 'Rick and Morty',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BZjRiNWMyZDItYmMxMy00MDJiLTg5N2QtYmRkMmNlYTA1Zjc2XkEyXkFqcGdeQXVyMTM1MTE1NDM1._V1_SX300.jpg',
    data_ai_hint: 'cartoon portal',
    year: '2013–',
    director: 'Dan Harmon (Creator), Justin Roiland (Creator)',
    actors: ['Justin Roiland', 'Chris Parnell', 'Spencer Grammer'],
    imdbRating: '9.1',
    genre: ['Animation', 'Adventure', 'Comedy'],
    plot: 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.',
    watched: false,
  },
  {
    id: 'tt4574334',
    title: 'Stranger Things',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzNWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    data_ai_hint: 'kids bicycle',
    year: '2016–',
    director: 'Matt Duffer (Creator), Ross Duffer (Creator)',
    actors: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    imdbRating: '8.7',
    genre: ['Drama', 'Fantasy', 'Horror'],
    plot: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    watched: false,
  },
  {
    id: 'tt0108778',
    title: 'Friends',
    type: 'tv',
    poster: 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
    data_ai_hint: 'couch friends',
    year: '1994–2004',
    director: 'David Crane (Creator), Marta Kauffman (Creator)',
    actors: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow'],
    imdbRating: '8.9',
    genre: ['Comedy', 'Romance'],
    plot: 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.',
    watched: false,
  },
];
